<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{$titulo}</title>
	<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
	<body>

		<div id="formulario">
		<h1>{$h1}</h1>
		<form action="login.php"  method="post">
			<span>Login: </span><input type="text" name="login" />
			<span>Senha: </span><input type="password" name="senha" />
			<input type="submit" name="logar" value="Logar" />
		</form>
		</div>
		<div id="rodape">
			<a href="professor/professor.php">Cadastre-se Já</a>
		</div>

	</body>
</html>